#!/usr/bin/env python3
"""Generates the named character reference table embedded in each port from data/entities.json.

    python3 scripts/gen_ports.py          # writes the five generated files
    python3 scripts/gen_ports.py --check  # fails if any generated file is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENT = json.loads((ROOT / "data" / "entities.json").read_text(encoding="utf-8"))["entities"]
NAMES = sorted(ENT)
HEADER = "Generated by scripts/gen_ports.py from data/entities.json (%d WHATWG named character references). Do not edit." % len(ENT)


def js(s):
    return json.dumps(s, ensure_ascii=True)


def rust():
    rows = "\n".join("    (%s, %s)," % (json.dumps(k), rs_lit(ENT[k])) for k in NAMES)
    return "// %s\n\n/// (name, replacement), sorted by name for binary search.\npub static ENTITIES: &[(&str, &str)] = &[\n%s\n];\n" % (HEADER, rows)


def rs_lit(s):
    return '"' + "".join("\\u{%x}" % ord(c) if ord(c) > 0x7E or ord(c) < 0x20 or c in '"\\' else c for c in s) + '"'


def ts():
    body = ",".join("%s:%s" % (js(k), js(ENT[k])) for k in NAMES)
    return "// %s\n\n/** Named character references, keyed by name (with or without the trailing ';'). */\nexport const ENTITIES: Record<string, string> = {%s};\n" % (HEADER, body)


def py_lit(s):
    return '"' + "".join(("\\U%08x" if ord(c) > 0xFFFF else "\\u%04x") % ord(c) if ord(c) > 0x7E or ord(c) < 0x20
                         or c in '"\\' else c for c in s) + '"'


def py():
    return '"""%s"""\n\nENTITIES = {\n%s}\n' % (HEADER, "".join("    %s: %s,\n" % (js(k), py_lit(ENT[k])) for k in NAMES))


def go():
    def g(t):
        return '"' + "".join(("\\U%08x" % ord(c) if ord(c) > 0xFFFF else "\\u%04x" % ord(c))
                             if ord(c) > 0x7E or ord(c) < 0x20 or c in '"\\' else c for c in t) + '"'
    rows = "".join("\t{%s, %s},\n" % (g(k), g(ENT[k])) for k in NAMES)
    return ("// Code generated by scripts/gen_ports.py from data/entities.json. DO NOT EDIT.\n\npackage lombokhtml\n\n"
            "// entities maps WHATWG named character references (with or without ';') to their text.\n"
            "var entities = func() map[string]string {\n\tm := make(map[string]string, len(entityList))\n"
            "\tfor _, e := range entityList {\n\t\tm[e[0]] = e[1]\n\t}\n\treturn m\n}()\n\n"
            "var entityList = [...][2]string{\n%s}\n" % rows)


def php():
    def p(s):
        return '"' + "".join("\\u{%x}" % ord(c) if ord(c) > 0x7E or ord(c) < 0x20 or c in '"\\$' else c for c in s) + '"'
    rows = "".join("        %s => %s,\n" % (p(k), p(ENT[k])) for k in NAMES)
    return "<?php\n\n// %s\n\ndeclare(strict_types=1);\n\nnamespace LombokHTML;\n\n/** @internal */\nfinal class Entities\n{\n    public const TABLE = [\n%s    ];\n}\n" % (HEADER, rows)


TARGETS = {"rust/src/entities_data.rs": rust, "typescript/src/entities.ts": ts, "python/lombokhtml/_entities.py": py,
           "go/entities.go": go, "php/src/Entities.php": php}


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, fn in TARGETS.items():
        text = fn()
        path = ROOT / rel
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        sys.exit("stale generated files: " + ", ".join(stale))
    print("ok" if check else "written: " + ", ".join(TARGETS))


if __name__ == "__main__":
    main()
